package claude

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"
	"unicode/utf8"

	"fleet/internal/adapter"
	"fleet/internal/transcript"
)

// Synthetic lines in the shape Claude Code 2.1.280 writes (fields the
// parser ignores mostly left out).
const (
	stamp = `"timestamp":"2026-09-27T10:00:00.250Z"`
	envl  = `"parentUuid":"p","isSidechain":false,"cwd":"/w","sessionId":"s","version":"2.1.280",` + stamp
)

var ms = time.Date(2026, 9, 27, 10, 0, 0, 250e6, time.UTC).UnixMilli()

func user(content string) string {
	return `{` + envl + `,"type":"user","message":{"role":"user","content":` + content + `},"uuid":"u"}`
}

func assistant(content string) string {
	return `{` + envl + `,"type":"assistant","message":{"id":"msg_1","model":"claude-opus-5-5","role":"assistant","content":` + content + `},"uuid":"u"}`
}

func system(fields string) string {
	return `{` + envl + `,"type":"system",` + fields + `,"uuid":"u"}`
}

func toolUseLine(name, input string) string {
	return assistant(`[{"type":"tool_use","id":"toolu_1","name":"` + name + `","input":` + input + `}]`)
}

type Es = []transcript.Entry

func noteAt(text string) Es { return Es{{Kind: transcript.Note, Text: text, TimeMs: ms}} }

func TestParseTranscript(t *testing.T) {
	tests := []struct {
		name, line string
		want       Es
	}{
		// what the user typed
		{"prompt", user(`"  fix the tests\n"`), Es{{Kind: transcript.User, Text: "fix the tests", TimeMs: ms}}},
		{"prompt blocks", user(`[{"type":"text","text":"what is this?"},{"type":"image","source":{"type":"base64","media_type":"image/png","data":"iVBO"}}]`),
			Es{{Kind: transcript.User, Text: "what is this?\n[image]", TimeMs: ms}}},
		{"prompt mentioning a tag", user(`"why does <command-name> show up?"`),
			Es{{Kind: transcript.User, Text: "why does <command-name> show up?", TimeMs: ms}}},
		{"system reminder removed", user(`"hi<system-reminder>be nice</system-reminder>"`), Es{{Kind: transcript.User, Text: "hi", TimeMs: ms}}},
		{"only a system reminder", user(`"<system-reminder>be nice</system-reminder>"`), nil},
		{"meta", `{` + envl + `,"type":"user","isMeta":true,"message":{"role":"user","content":"Base directory for this skill: /x"}}`, nil},
		{"sidechain", `{"type":"user","isSidechain":true,` + stamp + `,"message":{"role":"user","content":"subagent prompt"}}`, nil},
		{"compact summary", `{` + envl + `,"type":"user","isCompactSummary":true,"isVisibleInTranscriptOnly":true,"message":{"role":"user","content":"This session is being continued..."}}`, nil},

		// slash commands, local output, notifications
		{"command", user(`"<command-message>git-commit</command-message>\n<command-name>/git-commit</command-name>\n<command-args>push</command-args>"`), Es{{Kind: transcript.User, Text: "/git-commit push", TimeMs: ms}}},
		{"command without args", user(`"<command-name>/clear</command-name>\n            <command-message>clear</command-message>\n            <command-args></command-args>"`), Es{{Kind: transcript.User, Text: "/clear", TimeMs: ms}}},
		{"command stdout", user(`"<local-command-stdout>Set model to opus</local-command-stdout>"`), noteAt("Set model to opus")},
		{"empty command stdout", user(`"<local-command-stdout></local-command-stdout>"`), nil},
		{"caveat", user(`"<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>"`), nil},
		{"task notification", user(`"<task-notification>\n<task-id>b1</task-id>\n<tool-use-id>toolu_1</tool-use-id>\n<status>completed</status>\n<summary>Background command \"npm test\" completed (exit code 0)</summary>\n</task-notification>"`),
			Es{{Kind: transcript.Task, ID: "toolu_1", Name: "completed", Text: `Background command "npm test" completed (exit code 0)`, TimeMs: ms}}},
		{"task notification with result", user(`"<task-notification>\n<task-id>w1</task-id>\n<tool-use-id>toolu_2</tool-use-id>\n<status>failed</status>\n<summary>Dynamic workflow &quot;x&quot; failed</summary>\n<result>{\"a\":\"1 &lt; 2\"}</result>\n</task-notification>"`),
			Es{{Kind: transcript.Task, ID: "toolu_2", Name: "failed", Text: `Dynamic workflow "x" failed`, Output: `{"a":"1 < 2"}`, Error: true, TimeMs: ms}}},
		{"task notification without summary", user(`"<task-notification>\n<task-id>b1</task-id>\n</task-notification>"`),
			Es{{Kind: transcript.Task, Text: "background task finished", TimeMs: ms}}},
		{"bash input", user(`"<bash-input>git status</bash-input>"`), noteAt("! git status")},
		{"bash output", user(`"<bash-stdout>On branch main\n</bash-stdout><bash-stderr></bash-stderr>"`), noteAt("On branch main")},
		{"bash stdout and stderr", user(`"<bash-stdout>out</bash-stdout><bash-stderr>err</bash-stderr>"`), noteAt("out\nerr")},
		{"interrupted", user(`[{"type":"text","text":"[Request interrupted by user]"}]`), noteAt("interrupted")},
		{"interrupted tool use", user(`[{"type":"text","text":"[Request interrupted by user for tool use]"}]`), noteAt("interrupted")},

		// tool results
		{"tool result", user(`[{"tool_use_id":"toolu_1","type":"tool_result","content":"ok\n","is_error":false}]`),
			Es{{Kind: transcript.Result, ID: "toolu_1", Output: "ok", TimeMs: ms}}},
		{"tool result null is_error", user(`[{"tool_use_id":"toolu_1","type":"tool_result","content":"","is_error":null}]`),
			Es{{Kind: transcript.Result, ID: "toolu_1", TimeMs: ms}}},
		{"tool error", user(`[{"type":"tool_result","content":"<tool_use_error>File has not been read yet.</tool_use_error>","is_error":true,"tool_use_id":"toolu_2"}]`),
			Es{{Kind: transcript.Result, ID: "toolu_2", Output: "File has not been read yet.", Error: true, TimeMs: ms}}},
		{"tool result blocks", user(`[{"tool_use_id":"toolu_3","type":"tool_result","content":[{"type":"text","text":"see:"},{"type":"image","source":{"type":"base64","data":"iVBO"}},{"type":"tool_reference","tool_name":"WebFetch"}]}]`),
			Es{{Kind: transcript.Result, ID: "toolu_3", Output: "see:\n[image]\nWebFetch", TimeMs: ms}}},
		{"tool result reminder removed", user(`[{"tool_use_id":"toolu_4","type":"tool_result","content":"     1\tpackage main\n\n<system-reminder>\nWhenever you read a file...\n</system-reminder>\n"}]`),
			Es{{Kind: transcript.Result, ID: "toolu_4", Output: "     1\tpackage main", TimeMs: ms}}},
		{"tool result and text", user(`[{"tool_use_id":"toolu_5","type":"tool_result","content":"done"},{"type":"text","text":"now commit"}]`),
			Es{{Kind: transcript.Result, ID: "toolu_5", Output: "done", TimeMs: ms}, {Kind: transcript.User, Text: "now commit", TimeMs: ms}}},

		// the assistant
		{"text", assistant(`[{"type":"text","text":"\n\nAll tests pass."}]`), Es{{Kind: transcript.Assistant, Text: "All tests pass.", TimeMs: ms}}},
		{"string content", assistant(`"Done."`), Es{{Kind: transcript.Assistant, Text: "Done.", TimeMs: ms}}},
		{"blank text", assistant(`[{"type":"text","text":" \n"}]`), nil},
		{"thinking", assistant(`[{"type":"thinking","thinking":"","signature":"abc"}]`), nil},
		{"several blocks", assistant(`[{"type":"thinking","thinking":"hm"},{"type":"text","text":"Checking."},{"type":"tool_use","id":"toolu_9","name":"Bash","input":{"command":"ls"}}]`),
			Es{{Kind: transcript.Assistant, Text: "Checking.", TimeMs: ms}, {Kind: transcript.Tool, ID: "toolu_9", Name: "Bash", Text: "ls", TimeMs: ms}}},
		{"api error", `{` + envl + `,"type":"assistant","isApiErrorMessage":true,"error":"server_error","apiErrorStatus":529,"message":{"model":"<synthetic>","role":"assistant","content":[{"type":"text","text":"API Error: 529 Overloaded. Try again."}]}}`,
			noteAt("API Error: 529 Overloaded. Try again.")},
		{"synthetic reply", `{` + envl + `,"type":"assistant","message":{"model":"<synthetic>","role":"assistant","content":[{"type":"text","text":"No response requested."}]}}`, nil},

		// tool calls
		{"bash", toolUseLine("Bash", `{"command":"cd web &&\n  npm test","description":"Run tests","timeout":60000}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "Bash", Text: "cd web &&", Detail: "cd web &&\n  npm test", TimeMs: ms}}},
		{"read", toolUseLine("Read", `{"file_path":"/w/main.go","offset":10,"limit":20}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "Read", Text: "/w/main.go", Detail: "{\n  \"file_path\": \"/w/main.go\",\n  \"offset\": 10,\n  \"limit\": 20\n}", TimeMs: ms}}},
		{"edit", toolUseLine("Edit", `{"file_path":"/w/a.go","old_string":"a := 1\nb := 2","new_string":"a := 3\n","replace_all":false}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "Edit", Text: "/w/a.go", Detail: "-a := 1\n-b := 2\n+a := 3", TimeMs: ms}}},
		{"multi edit", toolUseLine("MultiEdit", `{"file_path":"/w/a.go","edits":[{"old_string":"x","new_string":"y"},{"old_string":"p","new_string":""}]}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "MultiEdit", Text: "/w/a.go", Detail: "@@\n-x\n+y\n@@\n-p", TimeMs: ms}}},
		{"write", toolUseLine("Write", `{"file_path":"/w/b.txt","content":"hello\nworld\n"}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "Write", Text: "/w/b.txt", Detail: "hello\nworld\n", TimeMs: ms}}},
		{"grep", toolUseLine("Grep", `{"pattern":"TODO","path":"src"}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "Grep", Text: "TODO in src", Detail: "{\n  \"pattern\": \"TODO\",\n  \"path\": \"src\"\n}", TimeMs: ms}}},
		{"todos", toolUseLine("TodoWrite", `{"todos":[{"content":"a"},{"content":"b"},{"content":"c"}]}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "TodoWrite", Text: "3 todos", Detail: `{
  "todos": [
    {
      "content": "a"
    },
    {
      "content": "b"
    },
    {
      "content": "c"
    }
  ]
}`, TimeMs: ms}}},
		{"agent", toolUseLine("Agent", `{"description":"Find the bug","prompt":"Look at..."}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "Agent", Text: "Find the bug", Detail: "{\n  \"description\": \"Find the bug\",\n  \"prompt\": \"Look at...\"\n}", TimeMs: ms}}},
		{"other tool", toolUseLine("mcp__srv__find", `{"where": {"slug":"x"}, "limit": 2}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "mcp__srv__find", Text: `{"where":{"slug":"x"},"limit":2}`, Detail: "{\n  \"where\": {\n    \"slug\": \"x\"\n  },\n  \"limit\": 2\n}", TimeMs: ms}}},
		{"plan", toolUseLine("ExitPlanMode", `{"plan":"# Plan\n\n1. Fix it","planFilePath":"/p.md"}`),
			Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "ExitPlanMode", Text: "Plan", Detail: "# Plan\n\n1. Fix it", TimeMs: ms}}},
		{"no input", toolUseLine("ListAgents", `{}`), Es{{Kind: transcript.Tool, ID: "toolu_1", Name: "ListAgents", TimeMs: ms}}},

		// system lines
		{"compacted", system(`"subtype":"compact_boundary","content":"Conversation compacted","level":"info","compactMetadata":{"trigger":"auto"}`), noteAt("conversation compacted")},
		{"api error retry", system(`"subtype":"api_error","level":"error","error":{"message":"529 {\"type\":\"error\"}","status":529,"formatted":"529 Overloaded"},"retryInMs":600,"retryAttempt":2,"maxRetries":10`),
			noteAt("API error: 529 Overloaded, retrying (2/10)")},
		{"informational", system(`"subtype":"informational","content":"Session resumed","level":"suggestion"`), noteAt("Session resumed")},
		{"local command", system(`"subtype":"local_command","content":"<command-name>/remote-control</command-name>\n  <command-message>remote-control</command-message>\n  <command-args></command-args>","level":"info"`), noteAt("/remote-control")},
		{"local command output", system(`"subtype":"local_command","content":"<local-command-stdout>Unknown command: /x</local-command-stdout>"`), noteAt("Unknown command: /x")},
		{"unknown command", system(`"subtype":"local_command","content":"/x some text"`), noteAt("/x some text")},
		{"stop hook summary", system(`"subtype":"stop_hook_summary","hookCount":1`), nil},
		{"turn duration", system(`"subtype":"turn_duration","durationMs":1000`), nil},

		// bookkeeping
		{"attachment", `{"type":"attachment","attachment":{"type":"queued_command"},` + stamp + `}`, nil},
		{"queue operation", `{"type":"queue-operation","operation":"enqueue","content":"next prompt",` + stamp + `}`, nil},
		{"last prompt", `{"type":"last-prompt","lastPrompt":"x","sessionId":"s"}`, nil},
		{"summary", `{"type":"summary","summary":"Fix tests","leafUuid":"u"}`, nil},

		// malformed
		{"empty", ``, nil},
		{"truncated", `{"type":"user","message":{"content":"hi`, nil},
		{"not an object", `[1,2]`, nil},
		{"null", `null`, nil},
		{"message not an object", `{"type":"user","message":"hi"}`, nil},
		{"content a number", user(`42`), nil},
		{"odd blocks", assistant(`[1,"x",null,{"type":"text","text":7},{"type":"tool_use"}]`), nil},
		{"odd timestamp", `{"type":"user","timestamp":12,"message":{"content":"hi"}}`, Es{{Kind: transcript.User, Text: "hi"}}},
	}
	a := New("", nil).(adapter.Transcripter)
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := a.ParseTranscript([]byte(tt.line))
			if !slices.Equal(got, tt.want) {
				t.Errorf("got\n%+v\nwant\n%+v", got, tt.want)
			}
		})
	}
}

func TestParseTranscriptClips(t *testing.T) {
	long := strings.Repeat("é", transcript.MaxText) // 2 bytes each
	cmd := strings.Repeat("ö", 150) + "\n" + strings.Repeat("x", transcript.MaxDetail)
	lines := []string{
		user(`"` + long + `"`),
		assistant(`[{"type":"text","text":"` + long + `"}]`),
		toolUseLine("Bash", `{"command":"`+strings.ReplaceAll(cmd, "\n", `\n`)+`"}`),
		user(`[{"tool_use_id":"t","type":"tool_result","content":"` + long + `"}]`),
		user(`"<local-command-stdout>` + long + `</local-command-stdout>"`),
	}
	a := New("", nil).(adapter.Transcripter)
	for i, l := range lines {
		es := a.ParseTranscript([]byte(l))
		if len(es) != 1 {
			t.Fatalf("line %d: %d entries", i, len(es))
		}
		checkEntry(t, es[0])
	}
}

// checkEntry checks the limits every entry must keep.
func checkEntry(t *testing.T, e transcript.Entry) {
	t.Helper()
	const slack = 32 // Clip's "… (n more bytes)"
	for _, f := range []struct {
		name, v string
		max     int
	}{{"Text", e.Text, transcript.MaxText}, {"Detail", e.Detail, transcript.MaxDetail}, {"Output", e.Output, transcript.MaxOutput}} {
		if !utf8.ValidString(f.v) {
			t.Errorf("%s %s is not UTF-8", e.Kind, f.name)
		}
		if len(f.v) > f.max+slack {
			t.Errorf("%s %s has %d bytes", e.Kind, f.name, len(f.v))
		}
	}
	if e.Kind == transcript.Tool && (strings.Contains(e.Text, "\n") || len(e.Text) > 200) {
		t.Errorf("tool summary %q is not one short line", e.Text)
	}
	switch e.Kind {
	case transcript.User, transcript.Assistant, transcript.Tool, transcript.Result, transcript.Note:
	default:
		t.Errorf("kind %q", e.Kind)
	}
}

func TestTranscriptDir(t *testing.T) {
	a := New("", nil).(adapter.Transcripter)
	t.Setenv("HOME", "/h")
	t.Setenv("CLAUDE_CONFIG_DIR", "")
	if got := a.TranscriptDir(""); got != "/h/.claude/projects" {
		t.Errorf("TranscriptDir = %q", got)
	}
	t.Setenv("CLAUDE_CONFIG_DIR", "/cfg")
	if got := a.TranscriptDir(""); got != "/cfg/projects" {
		t.Errorf("TranscriptDir with CLAUDE_CONFIG_DIR = %q", got)
	}
	if got := a.TranscriptDir("/sb"); got != "/sb/.claude/projects" {
		t.Errorf("TranscriptDir(/sb) = %q", got)
	}
}

func TestFindTranscript(t *testing.T) {
	const sid = "3f1c2a4e-7b5d-4e8a-9c1f-2d3e4f5a6b7c"
	dir := t.TempDir()
	write := func(rel string, age time.Duration) string {
		p := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("{}\n"), 0o600); err != nil {
			t.Fatal(err)
		}
		mt := time.Now().Add(-age)
		if err := os.Chtimes(p, mt, mt); err != nil {
			t.Fatal(err)
		}
		return p
	}
	write("-work-a/"+sid+".jsonl", time.Hour)
	newer := write("-work-b/"+sid+".jsonl", time.Minute)
	write("-work-c/"+sid+"/subagents/agent-a1.jsonl", 0)
	write("-work-c/other.jsonl", 0)
	if err := os.MkdirAll(filepath.Join(dir, "-work-d", sid+".jsonl"), 0o755); err != nil {
		t.Fatal(err)
	}

	a := New("", nil).(adapter.Transcripter)
	if got, ok := a.FindTranscript(dir, sid); !ok || got != newer {
		t.Errorf("FindTranscript = %q, %v, want %q", got, ok, newer)
	}
	for _, id := range []string{"", "agent-a1", "missing", "*", "3f1c*", "../-work-a/" + sid, "a/b", "a?b", "[3]f", ".", "..", sid + "\\x", strings.Repeat("a", 200)} {
		if got, ok := a.FindTranscript(dir, id); ok {
			t.Errorf("FindTranscript(%q) = %q", id, got)
		}
	}
}

// TestRealTranscripts parses every Claude Code transcript of the user
// running the test, to check the parser against real data after a Claude
// Code update. It prints nothing of their content.
func TestRealTranscripts(t *testing.T) {
	if os.Getenv("FLEET_REAL_TRANSCRIPTS") == "" {
		t.Skip("set FLEET_REAL_TRANSCRIPTS=1 to parse this machine's transcripts")
	}
	a := New("", nil).(adapter.Transcripter)
	files, _ := filepath.Glob(filepath.Join(a.TranscriptDir(""), "*", "*.jsonl"))
	kinds := map[string]int{}
	orphans := 0
	for _, f := range files {
		tools := map[string]bool{}
		for from := int64(0); ; {
			pg, err := transcript.Forward(f, from, a.ParseTranscript)
			if err != nil {
				t.Fatalf("%s: %v", f, err)
			}
			for _, e := range pg.Entries {
				checkEntry(t, e)
				kinds[e.Kind]++
				switch e.Kind {
				case transcript.Tool:
					tools[e.ID] = true
				case transcript.Result:
					if !tools[e.ID] {
						orphans++
					}
				}
			}
			if from = pg.End; !pg.More {
				break
			}
		}
	}
	t.Logf("%d files, entries %v, %d results without a tool call", len(files), kinds, orphans)
}
